# .github/workflows/deploy.yml
name: Deploy SkillMatch to AWS S3  # Name of the workflow
on:  # Event triggers for the workflow
  push:  # Trigger on push events
    branches: ["main"]  # Only trigger on pushes to the main branch

jobs:  # Define the jobs to run
  deploy:  # Job name
    runs-on: ubuntu-latest  # Run on the latest Ubuntu runner
    steps:  # Steps to execute in the job
      - name: Checkout code  # Step 1: Checkout the repository code
        uses: actions/checkout@v4  # Use the checkout action (v4)

      - name: Set up Node.js  # Step 2: Set up Node.js environment
        uses: actions/setup-node@v3  # Use the setup-node action (v3)
        with:  # Configuration for the action
          node-version: "18"  # Use Node.js version 18

      - name: Install dependencies  # Step 3: Install project dependencies
        run: npm install  # Run npm install to get dependencies

      - name: Build Angular app  # Step 4: Build the Angular app
        run: npm run build -- --prod  # Run the Angular build command in production mode

      - name: Configure AWS Credentials  # Step 5: Configure AWS credentials for S3 access
        uses: aws-actions/configure-aws-credentials@v1  # Use the configure-aws-credentials action (v1)
        with:  # Configuration for the action
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Access Key ID from GitHub secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Secret Access Key from GitHub secrets
          aws-region: eu-north-1  # AWS region (adjust if your bucket is in a different region)

      - name: Deploy to S3  # Step 6: Deploy the built files to S3
        run: aws s3 sync dist/skillmatch/ s3://my-skillmatch-project-2025 --delete  # Sync the dist/skillmatch/ folder to S3