# .github/workflows/deploy.yml
name: Build and Deploy SkillMatch to AWS S3
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Build Angular app
        run: npm run build -- --configuration production
      - name: List dist directory contents
        run: ls -la dist/skill-match/
      - name: Check if browser folder exists
        run: |
          if [ -d "dist/skill-match/browser" ]; then
            echo "Browser folder exists"
            ls -la dist/skill-match/browser/
          else
            echo "Browser folder does not exist"
            ls -la dist/skill-match/
            exit 1
          fi
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: dist/skill-match/browser/
          retention-days: 1
          if-no-files-found: error
      - name: Confirm build job success
        run: echo "Build job completed successfully"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Confirm deploy job is running
        run: echo "Deploy job is running"
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: dist/skill-match/browser/
      - name: Verify downloaded artifacts
        run: ls -la dist/skill-match/browser/
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name: Deploy to S3
        run: aws s3 sync dist/skill-match/browser/ s3://my-skillmatch-project-2025/ --delete